INSERT INTO Referenti VALUES
(14,"Caposala terapia intensiva"),
(15,"Caporeparto pediatria"),
(16,"Direttore generale"),
(17,"Dirigente sanitario"),
(18,"Medico dirigente del distretto"),
(19,"Dirigente tecnico"),
(20,"Caporeparto neurochirurgia"),
(21,"Caporeparto cardiochirurgia"),
(22,"Caporeparto radiologia"),
(23,"Caporeparto oncologia"),
(24,"Caporeparto dermatologia"),
(25,"Caporeparto gastroenterologia"),
(26,"Caposala anestesia e rianimazione"),
(27,"Caposala cardiologia"),
(28,"Responsabile dermatologia"),
(29,"Responsabile ematologia"),
(30,"Responsabile nefrologia"),
(31,"Responsabile oculistica"),
(32,"Responsabile urologia"),
(33,"Caposala reumatologia");
